"""部署预检、备份和安全恢复工具的纯标准库测试。"""
import os
import stat
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from scripts.deploy_preflight import load_dotenv_file, validate
from scripts.ops_backup import create_backup
from scripts.ops_restore import restore_backup
from scripts.smoke_test import normalize_base_url


def _valid_env() -> dict[str, str]:
    return {
        "COMPOSE_PROJECT_NAME": "mentor-agent-production",
        "IMAGE_TAG": "c2d913ac145a",
        "APP_PORT": "8501",
        "LLM_API_KEY": "sk-live-not-a-placeholder-value",
        "LLM_BASE_URL": "https://api.deepseek.com/v1",
        "LLM_MODEL": "deepseek-chat",
        "AUTH_SECRET": "a" * 64,
        "ALLOWED_EMAIL_DOMAINS": "zju.edu.cn",
        "ADMIN_EMAILS": "admin@zju.edu.cn",
        "SESSION_DAYS": "7",
        "EMBED_BACKEND": "local",
        "EMBED_MODEL": "BAAI/bge-small-zh-v1.5",
        "SMTP_HOST": "smtp.example.net",
        "SMTP_PORT": "465",
        "SMTP_USER": "mailer@example.net",
        "SMTP_PASSWORD": "smtp-auth-code",
        "SMTP_FROM": "mailer@example.net",
    }


def _root_with_release_files(base: Path) -> Path:
    root = base / "repo"
    (root / "knowledge_base" / "政策").mkdir(parents=True)
    (root / "knowledge_base" / "政策" / "official.md").write_text("official", encoding="utf-8")
    (root / "requirements.lock").write_text(
        "# This file is autogenerated by pip-compile with Python 3.12\n",
        encoding="utf-8",
    )
    return root


def test_load_dotenv_file():
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / ".env"
        path.write_text("\ufeff# comment\nexport A='one'\nB=two # note\nEMPTY=\n", encoding="utf-8")
        assert load_dotenv_file(path) == {"A": "one", "B": "two", "EMPTY": ""}


def test_production_preflight_accepts_valid_config():
    with tempfile.TemporaryDirectory() as tmp:
        root = _root_with_release_files(Path(tmp))
        checks = validate(_valid_env(), root, "production", min_docs=1)
        assert not [c for c in checks if c.level == "ERROR"], checks


def test_production_preflight_blocks_unsafe_config():
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp) / "repo"
        (root / "knowledge_base" / "政策").mkdir(parents=True)
        (root / "knowledge_base" / "政策" / "示例_政策.md").write_text("demo", encoding="utf-8")
        env = _valid_env()
        env.update({
            "LLM_API_KEY": "sk-xxxxxxxx",
            "LLM_BASE_URL": "http://localhost:1234/v1",
            "AUTH_SECRET": "short",
            "EMBED_BACKEND": "hash",
            "SMTP_HOST": "",
        })
        checks = validate(env, root, "production", min_docs=1)
        names = {c.name for c in checks if c.level == "ERROR"}
        assert {"LLM_API_KEY", "LLM_BASE_URL host", "AUTH_SECRET",
                "EMBED_BACKEND", "SMTP_HOST", "knowledge_base",
                "requirements.lock"}.issubset(names), checks


def test_normalize_base_url():
    assert normalize_base_url("https://mentor.example.com/") == "https://mentor.example.com"
    try:
        normalize_base_url("mentor.example.com")
        assert False, "缺少 scheme 应失败"
    except ValueError:
        pass


def test_backup_and_restore_to_empty_directory():
    with tempfile.TemporaryDirectory() as tmp:
        base = Path(tmp)
        root = base / "source"
        for name in ("knowledge_base", "chroma_db", "data"):
            (root / name).mkdir(parents=True)
        (root / "knowledge_base" / "policy.md").write_text("policy", encoding="utf-8")
        (root / "chroma_db" / "index.bin").write_bytes(b"index")
        (root / "data" / "auth.db").write_bytes(b"sqlite")

        try:
            create_backup(root, base / "backups")
            assert False, "未确认 app 停止时必须拒绝"
        except ValueError:
            pass

        archive = create_backup(root, base / "backups", confirm_app_stopped=True)
        assert stat.S_IMODE(archive.stat().st_mode) == 0o600
        destination = base / "restored"
        manifest = restore_backup(archive, destination)
        assert manifest["schema"] == 1
        assert (destination / "knowledge_base" / "policy.md").read_text() == "policy"
        assert (destination / "data" / "auth.db").read_bytes() == b"sqlite"

        (base / "not-empty").mkdir()
        (base / "not-empty" / "keep.txt").write_text("keep")
        try:
            restore_backup(archive, base / "not-empty")
            assert False, "禁止覆盖非空目录"
        except ValueError:
            pass


if __name__ == "__main__":
    fns = [v for k, v in list(globals().items()) if k.startswith("test_")]
    for fn in fns:
        fn()
        print(f"ok  {fn.__name__}")
    print(f"\n{len(fns)} 个测试全部通过")
