"""部署预检、备份和安全恢复工具的纯标准库测试。"""
import os
import stat
import subprocess
import sys
import tempfile
from dataclasses import replace
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from scripts.deploy_preflight import load_dotenv_file, validate
from scripts.ops_backup import create_backup
from scripts.ops_cert_check import CertificateCheckError, check_certificate
from scripts.ops_health_check import HealthCheckError, check_health, validate_health_url
from scripts.ops_restore import restore_backup
from scripts.ops_systemd_backup import (
    BackupConfig,
    BackupCycleError,
    exclusive_lock,
    run_backup_cycle,
)
from scripts.smoke_test import normalize_base_url


def _valid_env() -> dict[str, str]:
    return {
        "COMPOSE_PROJECT_NAME": "mentor-agent-production",
        "IMAGE_TAG": "c2d913ac145a",
        "APP_PORT": "8501",
        "LLM_API_KEY": "sk-live-not-a-placeholder-value",
        "LLM_BASE_URL": "https://api.deepseek.com/v1",
        "LLM_MODEL": "deepseek-chat",
        "AUTH_SECRET": "a" * 64,
        "ALLOWED_EMAIL_DOMAINS": "zju.edu.cn",
        "ADMIN_EMAILS": "admin@zju.edu.cn",
        "SESSION_DAYS": "7",
        "EMBED_BACKEND": "local",
        "EMBED_MODEL": "BAAI/bge-small-zh-v1.5",
        "SMTP_HOST": "smtp.example.net",
        "SMTP_PORT": "465",
        "SMTP_USER": "mailer@example.net",
        "SMTP_PASSWORD": "smtp-auth-code",
        "SMTP_FROM": "mailer@example.net",
    }


def _root_with_release_files(base: Path) -> Path:
    root = base / "repo"
    (root / "knowledge_base" / "政策").mkdir(parents=True)
    (root / "knowledge_base" / "政策" / "official.md").write_text(
        "---\nvalid: true\nreview_status: verified\n---\nofficial\n",
        encoding="utf-8",
    )
    (root / "requirements.lock").write_text(
        "# This file is autogenerated by pip-compile with Python 3.12\n",
        encoding="utf-8",
    )
    return root


def test_load_dotenv_file():
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / ".env"
        path.write_text("\ufeff# comment\nexport A='one'\nB=two # note\nEMPTY=\n", encoding="utf-8")
        assert load_dotenv_file(path) == {"A": "one", "B": "two", "EMPTY": ""}


def test_production_preflight_accepts_valid_config():
    with tempfile.TemporaryDirectory() as tmp:
        root = _root_with_release_files(Path(tmp))
        checks = validate(_valid_env(), root, "production", min_docs=1)
        assert not [c for c in checks if c.level == "ERROR"], checks


def test_production_preflight_blocks_unsafe_config():
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp) / "repo"
        (root / "knowledge_base" / "政策").mkdir(parents=True)
        (root / "knowledge_base" / "政策" / "示例_政策.md").write_text("demo", encoding="utf-8")
        env = _valid_env()
        env.update({
            "LLM_API_KEY": "sk-xxxxxxxx",
            "LLM_BASE_URL": "http://localhost:1234/v1",
            "AUTH_SECRET": "short",
            "EMBED_BACKEND": "hash",
            "SMTP_HOST": "",
        })
        checks = validate(env, root, "production", min_docs=1)
        names = {c.name for c in checks if c.level == "ERROR"}
        assert {"LLM_API_KEY", "LLM_BASE_URL host", "AUTH_SECRET",
                "EMBED_BACKEND", "SMTP_HOST", "knowledge_base",
                "requirements.lock"}.issubset(names), checks


def test_normalize_base_url():
    assert normalize_base_url("https://mentor.example.com/") == "https://mentor.example.com"
    try:
        normalize_base_url("mentor.example.com")
        assert False, "缺少 scheme 应失败"
    except ValueError:
        pass


def test_backup_and_restore_to_empty_directory():
    with tempfile.TemporaryDirectory() as tmp:
        base = Path(tmp)
        root = base / "source"
        for name in ("knowledge_base", "chroma_db", "data"):
            (root / name).mkdir(parents=True)
        (root / "knowledge_base" / "policy.md").write_text("policy", encoding="utf-8")
        (root / "chroma_db" / "index.bin").write_bytes(b"index")
        (root / "data" / "auth.db").write_bytes(b"sqlite")

        try:
            create_backup(root, base / "backups")
            assert False, "未确认 app 停止时必须拒绝"
        except ValueError:
            pass

        archive = create_backup(root, base / "backups", confirm_app_stopped=True)
        assert stat.S_IMODE(archive.stat().st_mode) == 0o600
        destination = base / "restored"
        manifest = restore_backup(archive, destination)
        assert manifest["schema"] == 1
        assert (destination / "knowledge_base" / "policy.md").read_text() == "policy"
        assert (destination / "data" / "auth.db").read_bytes() == b"sqlite"

        (base / "not-empty").mkdir()
        (base / "not-empty" / "keep.txt").write_text("keep")
        try:
            restore_backup(archive, base / "not-empty")
            assert False, "禁止覆盖非空目录"
        except ValueError:
            pass


class _FakeSystemdRunner:
    def __init__(self, *, state: str = "active", backup_returncode: int = 0):
        self.state = state
        self.backup_returncode = backup_returncode
        self.calls: list[list[str]] = []

    def __call__(self, args, *, check, text, capture_output):  # noqa: ANN001
        assert check is False
        assert text is True
        command = list(args)
        self.calls.append(command)
        if command[:2] == ["/systemctl", "is-active"]:
            return subprocess.CompletedProcess(
                command,
                0 if self.state == "active" else 3,
                stdout=f"{self.state}\n",
                stderr="",
            )
        if command[:2] == ["/systemctl", "stop"]:
            self.state = "inactive"
            return subprocess.CompletedProcess(command, 0, stdout="", stderr="")
        if command[:2] == ["/systemctl", "start"]:
            self.state = "active"
            return subprocess.CompletedProcess(command, 0, stdout="", stderr="")
        return subprocess.CompletedProcess(
            command,
            self.backup_returncode,
            stdout="",
            stderr="backup failed" if self.backup_returncode else "",
        )


def _backup_config(base: Path) -> BackupConfig:
    root = base / "app"
    output = base / "backups"
    root.mkdir()
    output.mkdir()
    script = root / "ops_backup.py"
    script.write_text("# test\n", encoding="utf-8")
    return BackupConfig(
        service="mentor-agent.service",
        root=root,
        output_dir=output,
        backup_script=script,
        python="/python",
        # root（例如容器内测试）必须显式降权；普通 CI 用户可直接运行假归档命令。
        run_as_user="nobody" if os.geteuid() == 0 else "",
        systemctl="/systemctl",
        runuser="/runuser",
        lock_file=base / "backup.lock",
    )


def test_systemd_backup_restores_active_service_on_success_and_failure():
    with tempfile.TemporaryDirectory() as tmp:
        config = _backup_config(Path(tmp))
        runner = _FakeSystemdRunner()
        run_backup_cycle(config, runner=runner)
        assert runner.state == "active"
        assert ["/systemctl", "stop", config.service] in runner.calls
        assert ["/systemctl", "start", config.service] in runner.calls

        failing = _FakeSystemdRunner(backup_returncode=7)
        try:
            run_backup_cycle(config, runner=failing)
            assert False, "归档失败必须返回错误"
        except BackupCycleError:
            pass
        assert failing.state == "active", "归档失败后仍须恢复原本 active 的服务"
        assert ["/systemctl", "start", config.service] in failing.calls


def test_systemd_backup_keeps_originally_stopped_service_stopped():
    with tempfile.TemporaryDirectory() as tmp:
        config = _backup_config(Path(tmp))
        runner = _FakeSystemdRunner(state="inactive")
        run_backup_cycle(config, runner=runner)
        assert runner.state == "inactive"
        assert not [call for call in runner.calls if call[:2] == ["/systemctl", "stop"]]
        assert not [call for call in runner.calls if call[:2] == ["/systemctl", "start"]]


def test_systemd_backup_refuses_unknown_state_and_concurrent_lock():
    with tempfile.TemporaryDirectory() as tmp:
        base = Path(tmp)
        config = _backup_config(base)
        runner = _FakeSystemdRunner(state="activating")
        try:
            run_backup_cycle(config, runner=runner)
            assert False, "无法确认停止状态时必须安全失败"
        except BackupCycleError:
            pass
        assert len(runner.calls) == 1

        root_config = replace(config, run_as_user="root")
        try:
            run_backup_cycle(root_config, runner=_FakeSystemdRunner())
            assert False, "归档进程不得以 UID 0 运行"
        except ValueError:
            pass

        with exclusive_lock(config.lock_file):
            try:
                with exclusive_lock(config.lock_file):
                    assert False, "并发备份必须被锁拒绝"
            except BackupCycleError:
                pass


class _FakeResponse:
    def __init__(self, status: int, body: bytes):
        self.status = status
        self.body = body

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, traceback):  # noqa: ANN001
        return False

    def read(self, limit: int) -> bytes:
        return self.body[:limit]


class _FakeOpener:
    def __init__(self, status: int = 200, body: bytes = b"ok"):
        self.response = _FakeResponse(status, body)

    def open(self, request, timeout):  # noqa: ANN001
        assert request.full_url.startswith("http://127.0.0.1:")
        assert 0 < timeout <= 60
        return self.response


def test_local_health_check_is_loopback_only_and_checks_body():
    status, elapsed = check_health(
        "http://127.0.0.1:8501/_stcore/health",
        opener=_FakeOpener(body=b"OK"),
    )
    assert status == 200 and elapsed >= 0
    try:
        validate_health_url("https://mentor.example.com/_stcore/health")
        assert False, "同机健康检查不得访问非回环地址"
    except ValueError:
        pass
    try:
        check_health(
            "http://127.0.0.1:8501/_stcore/health",
            opener=_FakeOpener(body=b"unexpected"),
        )
        assert False, "健康响应缺少预期文本时必须失败"
    except HealthCheckError:
        pass


class _FakeOpenSSLRunner:
    def __init__(self, *, expiring: bool = False, parse_error: bool = False):
        self.expiring = expiring
        self.parse_error = parse_error
        self.calls: list[list[str]] = []

    def __call__(self, args, *, check, text, capture_output):  # noqa: ANN001
        assert check is False and text is True and capture_output is True
        command = list(args)
        self.calls.append(command)
        if "-subject" in command:
            return subprocess.CompletedProcess(
                command,
                1 if self.parse_error else 0,
                stdout="" if self.parse_error else "subject=CN=mentor.example\nnotAfter=Nov 2\n",
                stderr="bad certificate" if self.parse_error else "",
            )
        return subprocess.CompletedProcess(
            command,
            1 if self.expiring else 0,
            stdout="",
            stderr="",
        )


def test_certificate_check_fails_closed_for_expiry_or_parse_error():
    with tempfile.TemporaryDirectory() as tmp:
        cert = Path(tmp) / "fullchain.pem"
        cert.write_text("dummy", encoding="utf-8")
        runner = _FakeOpenSSLRunner()
        summary = check_certificate(cert, warn_days=30, runner=runner)
        assert "mentor.example" in summary
        checkend = [call for call in runner.calls if "-checkend" in call][0]
        assert str(30 * 24 * 60 * 60) in checkend

        for failing in (
            _FakeOpenSSLRunner(expiring=True),
            _FakeOpenSSLRunner(parse_error=True),
        ):
            try:
                check_certificate(cert, runner=failing)
                assert False, "过期窗口或解析错误必须失败"
            except CertificateCheckError:
                pass


def test_systemd_ops_templates_use_environment_file_and_safe_timers():
    deploy = Path(__file__).resolve().parents[1] / "deploy"
    services = (
        "mentor-agent-backup.service",
        "mentor-agent-health.service",
        "mentor-agent-cert-check.service",
    )
    timers = (
        "mentor-agent-backup.timer",
        "mentor-agent-health.timer",
        "mentor-agent-cert-check.timer",
    )
    for name in services:
        text = (deploy / name).read_text(encoding="utf-8")
        assert "EnvironmentFile=-/etc/mentor-agent/ops.env" in text
        assert "ExecStart=/usr/bin/python3 /usr/local/libexec/mentor-agent/" in text
        assert "${MENTOR_ROOT}/scripts/" not in text
    backup_service = (deploy / "mentor-agent-backup.service").read_text(encoding="utf-8")
    assert "ProtectSystem=strict" in backup_service
    assert "ReadWritePaths=/srv/mentor-backups /run/lock" in backup_service
    # backup runner 以 root 管理 systemd unit，再用 runuser 把归档阶段降权到 txc。
    # NoNewPrivileges=true 会禁止这次 setuid，导致 timer 在停服后归档失败。
    assert "NoNewPrivileges=true" not in backup_service
    for name in timers:
        text = (deploy / name).read_text(encoding="utf-8")
        assert "WantedBy=timers.target" in text
    backup_timer = (deploy / "mentor-agent-backup.timer").read_text(encoding="utf-8")
    cert_timer = (deploy / "mentor-agent-cert-check.timer").read_text(encoding="utf-8")
    assert "Persistent=true" in backup_timer
    assert "Persistent=true" in cert_timer
    caddy_production = (deploy / "Caddyfile.production").read_text(encoding="utf-8")
    assert "protocols h1 h2" in caddy_production


if __name__ == "__main__":
    fns = [v for k, v in list(globals().items()) if k.startswith("test_")]
    for fn in fns:
        fn()
        print(f"ok  {fn.__name__}")
    print(f"\n{len(fns)} 个测试全部通过")
